// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJs7P-4Pbb_eSsenqM4vkS18rcOF4jjf0',
    appId: '1:314905412054:web:f6dd8e531d1c83c245e477',
    messagingSenderId: '314905412054',
    projectId: 'sweetlayers-fa327',
    authDomain: 'sweetlayers-fa327.firebaseapp.com',
    storageBucket: 'sweetlayers-fa327.appspot.com',
    measurementId: 'G-P68CVPVCQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkqPflP_hKxrpKNfHqt2DrN03fmriFuQ',
    appId: '1:314905412054:android:86797df21610aca245e477',
    messagingSenderId: '314905412054',
    projectId: 'sweetlayers-fa327',
    storageBucket: 'sweetlayers-fa327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD311IiAOx_ac3VRMVjIe-KuxcSV0uEgQ4',
    appId: '1:314905412054:ios:69976661ccb2033745e477',
    messagingSenderId: '314905412054',
    projectId: 'sweetlayers-fa327',
    storageBucket: 'sweetlayers-fa327.appspot.com',
    iosBundleId: 'com.example.sweetLayers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD311IiAOx_ac3VRMVjIe-KuxcSV0uEgQ4',
    appId: '1:314905412054:ios:69976661ccb2033745e477',
    messagingSenderId: '314905412054',
    projectId: 'sweetlayers-fa327',
    storageBucket: 'sweetlayers-fa327.appspot.com',
    iosBundleId: 'com.example.sweetLayers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJs7P-4Pbb_eSsenqM4vkS18rcOF4jjf0',
    appId: '1:314905412054:web:3f4bfd08aa17b75e45e477',
    messagingSenderId: '314905412054',
    projectId: 'sweetlayers-fa327',
    authDomain: 'sweetlayers-fa327.firebaseapp.com',
    storageBucket: 'sweetlayers-fa327.appspot.com',
    measurementId: 'G-212F4WH08S',
  );
}
